---
- name: Locate Kolla Ansible prefix
  command: |
    {{ kolla_python }} -c 'import os,kolla_ansible; print(os.path.abspath(os.path.join(os.path.dirname(kolla_ansible.__file__),"../../../..")));'
  register: kolla_ansible_base_path
  delegate_to: "{{ groups['deployment'][0] }}"
  run_once: true

- name: Check for passwords.yml
  stat:
    path: "{{ kolla_passwords_file }}"
  register: kolla_passwords
  delegate_to: "{{ groups['deployment'][0] }}"
  run_once: true

- name: Copy passwords template from Kolla Ansible
  copy:
    src: "{{ kolla_ansible_path }}/etc_examples/kolla/passwords.yml"
    dest: "{{ kolla_passwords_file }}"
  when: not kolla_passwords.stat.exists
  delegate_to: "{{ groups['deployment'][0] }}"
  run_once: true

- name: Update passwords
  command: "kolla-genpwd -p {{ kolla_passwords_file }}"
  delegate_to: "{{ groups['deployment'][0] }}"
  run_once: true
