#!/bin/bash
#
# Copyright 2019 Ettore Simone <ettore.simone@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -n "$DIB_DOCKER_VERSION" ]; then
    PACKAGE_FILTER=$($DIB_PYTHON -c "import re; print(re.escape(r'$DIB_DOCKER_VERSION'));")
fi
case $DISTRO_NAME in
    debian|ubuntu)
        if [ -n "$DIB_DOCKER_VERSION" ]; then
            SPECIFIC_VERSION=$(apt-cache madison docker-ce | sed 's/ | / /g' | awk '/'$PACKAGE_FILTER'/{ print $2 }' | head -1)
            SPECIFIC_VERSION="=${SPECIFIC_VERSION}"
        else
            SPECIFIC_VERSION=""
        fi
        install-packages docker-ce$SPECIFIC_VERSION docker-ce-cli$SPECIFIC_VERSION containerd.io
        if [[ "${DIB_DOCKER_LOCK,,}" =~ ^(0|yes|true)$ ]]; then
            apt-mark hold docker-ce docker-ce-cli
        fi
        ;;
    centos*|rhel*)
        YUM=${YUM:-yum}
        if [ -n "$DIB_DOCKER_VERSION" ]; then
            SPECIFIC_VERSION=$(${YUM} list docker-ce --showduplicates | sort -r | awk '/'$PACKAGE_FILTER'/{ print $2 }' | head -1)
            SPECIFIC_VERSION="-${SPECIFIC_VERSION#*:}"
        else
            SPECIFIC_VERSION=""
        fi
        ${YUM} -v -y install --nobest docker-ce$SPECIFIC_VERSION docker-ce-cli$SPECIFIC_VERSION containerd.io
        ${YUM} mark install docker-ce docker-ce-cli
        if [[ "${DIB_DOCKER_LOCK,,}" =~ ^(0|yes|true)$ ]]; then
            ${YUM} versionlock add docker-ce docker-ce-cli
        fi
        ;;
esac

COMPOSE_URL=$(curl -fsS https://github.com/docker/compose/releases/latest | sed -n 's|.*<a href="\([^"]*\)".*|\1|p')
COMPOSE_VERSION=${COMPOSE_URL##*/}
curl -L "https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
