---
- block:
    - include_tasks: "cert-{{ ansible_os_family }}.yml"
      when: underground_import_ca|bool

    - name: Ensuring source directory exist
      file:
        path: "{{ git_repos_directory }}"
        state: directory
        mode: "1777"

    - name: Create Underground config directory
      file:
        path: "{{ item }}"
        state: directory
        mode: "0750"
        owner: "{{ config_owner_user }}"
        group: "{{ config_owner_group }}"
      loop:
        - "{{ config_path }}"
        - "{{ config_path }}/ceph"
        - "{{ config_path }}/kolla"
        - "{{ config_path }}/globals.d"
        - "{{ data_path }}"
        - "{{ log_path }}"
  become: true

- name: Create Underground Baremetal config directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  loop:
    - "{{ config_path }}/baremetal"
    - "{{ config_path }}/baremetal/images"
    - "{{ data_path }}/baremetal"
    - "{{ data_path }}/baremetal/images"
    - "{{ data_path }}/baremetal/cache"
    - "{{ log_path }}/baremetal"
  become: true
  when: "'baremetal' in underground_list_modules"

- name: Write Underground globals.yml
  copy:
    content: "{{ underground_globals|to_nice_yaml(explicit_start=true) }}"
    dest: "{{ config_path }}/globals.yml"
