---

- name: Set Inspector PXE filter to dnsmasq
  blockinfile:
    path: /etc/kolla/ironic-dnsmasq/dnsmasq.conf
    block: ""
  become: true

- name: Set Ironic config PXE filter
  lineinfile:
    path: /etc/kolla/ironic-inspector/inspector.conf
    regexp: 'driver = dnsmasq'
    line: 'driver = noop'
  become: true

- name: Change underground config
  lineinfile:
    path: "{{ kolla_config_path }}/globals.yml"
    regexp: 'ironic_inspector_pxe_filter: dnsmasq'
    line: 'ironic_inspector_pxe_filter: noop'

- name: Restart Ironic Services
  shell: "docker restart {{ item }}"
  args:
    executable: "/bin/bash"
  loop:
    - "{{ ironic_inspector_container }}"
    - "{{ ironic_dnsmasq_container }}"
  become: true

- name: Add NAT rule
  iptables:
    table: nat
    action: append
    chain: POSTROUTING
    out_interface: "{{ underground_public_interface }}"
    jump: MASQUERADE
  become: true

- name: Enable Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
  become: true
