---
# These are Ansible requirements needed to run kolla-ansible master and ceph-ansible master
collections:
  - name: https://opendev.org/openstack/ansible-collection-kolla
    type: git
    version: stable/zed
  - name: https://opendev.org/openstack/ansible-config_template
    version: 1.2.1
    type: git
  - name: ansible.utils
    version: '>=2.5.0'
  - name: community.general
  - name: ansible.posix
