#!/bin/bash
#
# Copyright 2019 Ettore Simone <ettore.simone@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

OPENSTACK_MODULES="openstack,${DIB_OPENSTACK_MODULES// /,}"

$DIB_PYTHON_PIP install $(eval echo python-{${OPENSTACK_MODULES//,,/,}}client)

# Ensure exports OS_ invalidate the openstack command execution
unset $(compgen -A variable | grep ^OS_)
openstack complete >/etc/bash_completion.d/osc.bash_completion

# Create a meta-command to upgrade openstack client packages
cat >/usr/local/bin/openstack-client-update <<EOF
#!/bin/bash

OPENSTACK_MODULES=\$($DIB_PYTHON_PIP freeze | awk -F== '/^python-.*client==/{ print \$1 }')
sudo -H $DIB_PYTHON_PIP install --upgrade --upgrade-strategy only-if-needed \$OPENSTACK_MODULES
EOF
chmod +x /usr/local/bin/openstack-client-update
