---
- name: Install required packages
  become: true
  package:
    name: "{{ packages_all }}"

- name: Install custom packages
  become: true
  package:
    name: "{{ packages_custom }}"
- debug:
  msg: "{{ virtualenv }}"
- name: Install Python packages
  become: true
