---
- name: Wait for ssh server to become available
  become: False
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 1
    timeout: 300
  delegate_to: "localhost"

- name: Collect facts
  setup:
    gather_subset:
      - all
      - min
      - hardware
      - network
      - virtual
      - ohai
      - facter

