---
enable_keepalived: "yes"
enable_ironic_ipxe: "yes"
enable_nova_serialconsole_proxy: "yes"

kolla_internal_vip_address: "{{ underground_internal_address }}"
kolla_external_vip_address: "{{ underground_public_address }}"
neutron_external_interface: "physnet1,ext-baremetal"
neutron_bridge_name: "br-ex,br-bm"
network_interface: "{{ underground_internal_interface }}" 

ironic_cleaning_network: "baremetal"
neutron_tenant_network_types: "vxlan,vlan,flat"
ironic_dnsmasq_interface: "baremetal"
ironic_dnsmasq_dhcp_range: "{{ underground_baremetal_address | ipmath(2) + ',' + underground_baremetal_address | ipmath(6) | default(underground_baremetal_dhcp_range) }}"
#ironic_dnsmasq_default_gateway: "{{ hostvars[inventory_hostname]['ansible_'+underground_baremetal_interface]['ipv4']['gateway'] | default(underground_baremetal_gateway) }}"
ironic_dnsmasq_default_gateway: "{{ hostvars[inventory_hostname]['ansible_'+ironic_dnsmasq_interface]['ipv4']['address'] | default(underground_baremetal_gateway) }}"
ironic_inspector_pxe_filter: "noop"
ironic_ipxe_url: "http://{{ underground_baremetal_address | put_address_in_context('url') }}:{{ ironic_ipxe_port }}"
tftp_server: "{{ underground_baremetal_address }}"
ironic_inspector_kernel_cmdline_extras: ['ipa-lldp-timeout=10.0', 'ipa-collect-lldp=0', 'ipa-inspection-collectors=default,logs,pci-devices,extra-hardware,dmi-decode,numa-topology']
