---
enable_openstack_core: "no"
enable_neutron_provider_networks: "yes"
kolla_base_distro: "ubuntu"
kolla_install_type: "source"
kolla_enable_tls_external: "yes"
kolla_copy_ca_into_containers: "yes"
kolla_internal_vip_address: "{{ underground_internal_address }}"
kolla_external_vip_interface: "{{ underground_public_interface }}"
neutron_external_interface: "{{ underground_external_interface }}"
network_interface: "{{ underground_internal_interface }}"
node_custom_config: "{{ kolla_config_path }}/config"
