---
enable_chrony: "{{ 'no' if 'ceph' in underground_list_modules else 'yes' }}"
#enable_keepalived: "yes"
kolla_external_vip_address: "{{ underground_public_address }}"
kolla_internal_vip_address: "{{ underground_internal_address }}"
network_interface: "{{ underground_internal_interface }}"
