---
- name: set kind binary fact
  set_fact:
    kind_binary: /usr/local/bin/kind

- name: set kubectl binary fact
  set_fact:
    kubectl_binary: /usr/local/bin/kubectl

- name: "Check if {{ cluster_name }} already exists"
  docker_container_info:
    name: "{{ cluster_name + '-control-plane' }}"
  register: cluster_check_result

- name : Create KinD Cluster dir
  file:
    path: "{{ kind_home_dir + '/' + cluster_name }}"
    state: directory

- name: Create KinD Config
  template:
    dest: "{{ kind_home_dir + '/' + cluster_name + '/' + kind_cluster_config }}"
    src: 'kind-cluster-config.yml.j2'
    mode: "755"
  when: kind_create_config

- name: "Set {{ cluster_name }} config file"
  set_fact:
    kind_cluster_config_file: "{{ kind_home_dir + '/' + cluster_name + '/' + kind_cluster_config }}"
  when: kind_create_config

