---
- name: Get latest KinD release
  uri:
    url: https://api.github.com/repos/kubernetes-sigs/kind/releases/latest
    return_content: yes
  register: kind_release
  when: kind_version is not defined 

- name: Get latest kubectl release
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_release
  when: kubectl_version is not defined 

- name: Set KinD version
  set_fact:
    kind_version: "{{ kind_release.json.tag_name }}"
  when: kind_version is not defined

- name: Set kubectl version
  set_fact:
    kubectl_version: "{{ kubectl_release.json.tag_name }}"
  when: kubectl_version is not defined

- name: 'Check KinD Pre-req'
  include_tasks: kind_pre_reqs.yml

- name: 'Create KinD {{ cluster_name }} Cluster'
  include_tasks: kind_create.yml
  when: kind_create

- name: 'Destroy KinD {{ cluster_name }} Cluster'
  include_tasks: kind_destroy.yml
  when: kind_destroy
