#!/bin/bash
#
# Copyright 2019 Ettore Simone <ettore.simone@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case $DISTRO_NAME in
    centos*)
        CLOUD_INIT_VERSION=${DIB_CLOUD_INIT_VERSION:-master}
        if [[ -f /etc/cloud/cloud.cfg ]]; then
            mv -f /etc/cloud/cloud.cfg /etc/cloud/cloud.cfg.save
            ${YUM:-yum} -v -y remove cloud-init
        fi
	git clone -b ${CLOUD_INIT_VERSION//\//-} https://github.com/canonical/cloud-init /usr/src/cloud-init
        patch -d /usr/src/cloud-init -p1 <$(dirname $0)/cloud-init-helpers-openstack.patch
        patch -d /usr/src/cloud-init -p1 <$(dirname $0)/cloud-init-net-sysconfig.patch
        $DIB_PYTHON_PIP install -r /usr/src/cloud-init/requirements.txt
        (
            cd /usr/src/cloud-init
            $DIB_PYTHON setup.py build
            $DIB_PYTHON setup.py install --init-system systemd --prefix /usr
        )
        rm -rf /usr/src/cloud-init
        if [[ -f /etc/cloud/cloud.cfg.save ]]; then
            mv -f /etc/cloud/cloud.cfg.save /etc/cloud/cloud.cfg
	fi
	test -z "${CLOUD_CFG:-}" || echo "${CLOUD_CFG}" >/etc/cloud/cloud.cfg
        systemctl daemon-reload
        for SERVICE in cloud-init-local cloud-init cloud-config cloud-final; do
            systemctl unmask ${SERVICE}.service || :
            systemctl enable ${SERVICE}.service
        done
        ;;
    ubuntu)
        CLOUD_INIT_DIR=$($DIB_PYTHON -c "import os, cloudinit; print(os.path.dirname(cloudinit.__file__));")
        case $DIB_RELEASE in
            bionic)
                patch -d $CLOUD_INIT_DIR -p2 <$(dirname $0)/cloud-init-helpers-openstack.patch
	        ;;
            xenial)
                patch -d $CLOUD_INIT_DIR -p2 <$(dirname $0)/cloud-init-net-eni.patch
	        ;;
        esac
esac
