---
- name: Ensure directory ~/.ssh exists
  file:
    state: directory
    path: "{{ config_dir }}/keys"
    mode: 0700

- name: Create local SSH RSA key certificate
  copy:
    dest: "{{ config_dir }}/keys/{{ underground_rsa_key_file }}"
    content: "{{ underground_rsa_key }}"
    mode: 0600

- name: Create local SSH RSA public certificate
  copy:
    dest: "{{ config_dir }}/keys/{{ underground_rsa_pub_file }}"
    content: "{{ underground_rsa_pub }}"
    mode: 0644
