- name: Create Deployer Instance
  os_server:
    auth:
       auth_url: "{{ underground_auth_auth_url }}"
       username: "{{ underground_auth_username }}"
       password: "{{ underground_auth_password }}"
       project_name: admin
       os_user_domain_name: Default
       os_project_domain_name: Default
    auth_type: password
    interface: internal
    state: present
    name: deployer
    image: "{{ deployer_image_name }}"
    key_name: ironic_key
    timeout: 400
    flavor: generic
    nics:
       - net-name: external
    security_groups: mgmt
    meta:
       hostname: deployer
    wait: true
  register: os_info
  #when: os_result.openstack_servers|length == 0
