#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -d /etc/default/grub.d/50-cloudimg-settings.cfg ]; then
    sed -e 's/ttyS0/ttyS1/g' -i /etc/default/grub.d/50-cloudimg-settings.cfg
fi
