---
- name: Check for deploment topology
  fail:
    msg: "Deployment topology is not Converged"
  when: groups['control']|difference(groups['network']) or
        groups['compute']|difference(groups['storage']) or
        (groups['control'])|length not in [1, 3, 5] or
        (groups['compute'])|length < 2 or
        (groups['compute'])|length > 50
