---
- name: Install required packages
  become: true
  package:
    name: "{{ packages_all }}"

- name: Install custom packages
  become: true
  package:
    name: "{{ packages_custom }}"

- name: Install Python packages
  become: true
  pip:
    name: "{{ packages_python }}"
