---
- name: 'Ensure collections top-level directory'
  file:
    path: '/etc/ansible/collections/ansible_collections'
    state: directory
    mode: 0755

- name: 'download required ansible collections'
  command: "ansible-galaxy collection install {{ item }} -p /etc/ansible/collections --force"
  loop: "{{ app.collections }}"
