---
- name: Set OS distribution dependent variables
  include_vars: "{{ ansible_facts['distribution'] }}.yaml"

- name: Install cert package
  package:
    name: ca-certificates
    state: present

- name: Add e4lan cert
  get_url:
    url: http://{{ idm.ipa }}/ipa/config/ca.crt
    dest: "{{ certdir }}/e4lan.crt"
    mode: '0644'

- name: update certificates
  command: "{{ certcmd }}"
  args:
    chdir: "{{ certdir }}"
