---
- include_tasks: support.yml

- include_tasks: overwrite_defaults.yml

- include_tasks: modules_defaults.yml

#- include_tasks: private_registry.yml
#  when:
#    - "'deployment' in group_names"
#    - "underground_deployment != 'aio'"

- include_tasks: external_ceph.yml
  when:
    - "'storage' in underground_list_modules"
    - "not underground_dryrun"

