- name: Cloning kolla-ansible source repository
  git:
    repo: "{{ kolla_ansible_git_repository }}"
    dest: "{{ git_repos_directory }}/{{ project_name }}"
    update: yes
    version: "{{ kolla_ansible_source_version }}"

- name: Install kolla-ansible
  become: true
  command: "{{ kolla_python }} -m pip install {{ git_repos_directory }}/{{ project_name }}"
