---
- fail:
    msg: "OpenStack release `{{ openstack_release }}' is not supported"
  when: openstack_release not in kolla_releases

- include_tasks: overwrite_defaults.yml

- name: Manages Python dependencies
  become: "{{ virtualenv is undefined }}"
  pip:
    name: "{{ query('lines', [\"awk '/^[[:alnum:]]+/{ print $1 }' {{ playbook_dir }}/../requirements.txt\"]) }}"
    executable: "{{ virtualenv is none | ternary('pip3', omit) }}"
    virtualenv: "{{ virtualenv is none | ternary(omit, virtualenv) }}"
    virtualenv_site_packages: "{{ virtualenv is none | ternary(omit, virtualenv_site_packages) }}"
    virtualenv_command: "{{ virtualenv is none | ternary(omit, 'python' ~ kolla_releases[openstack_release]['python_version'] ~ ' -m venv') }}" 

- name: Install required packages
  become: true
  package:
    name: "{{ packages_all }}"

- name: Install custom packages
  become: true
  package:
    name: "{{ packages_custom }}"

- name: Install custom Python packages
  become: "{{ virtualenv is undefined }}"
  pip:
    name: "{{ packages_python }}"
    executable: "{{ virtualenv is none | ternary('pip3', omit) }}"
    virtualenv: "{{ virtualenv is none | ternary(omit, virtualenv) }}"
    virtualenv_site_packages: "{{ virtualenv is none | ternary(omit, virtualenv_site_packages) }}"
    virtualenv_command: "{{ virtualenv is none | ternary(omit, 'python' ~ kolla_releases[openstack_release]['python_version'] ~ ' -m venv') }}" 

