---
- fail:
    msg: "OpenStack release `{{ openstack_release }}' is not supported"
  when: openstack_release not in kolla_releases

- include_tasks: overwrite_defaults.yml

- name: Manages Python dependencies
  become: true
  pip:
    name: "{{ query('lines', [\"awk '/^[[:alnum:]]+/{ print $1 }' {{ playbook_dir }}/../requirements.txt\"]) }}"

- name: Install required packages
  become: true
  package:
    name: "{{ packages_all }}"

- name: Install custom packages
  become: true
  package:
    name: "{{ packages_custom }}"

- name: Install custom Python packages
  become: true
  pip:
    name: "{{ packages_python }}"
