#!/bin/bash
  
if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# https://nvidia.github.io/nvidia-docker/
# https://nvidia.github.io/nvidia-container-runtime/
NVIDIA_PKGLIST=(nvidia-container-toolkit nvidia-docker2)
NVIDIA_PKGLIST+=(libnvidia-{cfg1,compute}-${DIB_NVIDIA_VERSION})
NVIDIA_PKGLIST+=(nvidia-{compute-utils,dkms,driver,headless,headless-no-dkms,kernel-common,kernel-source,utils}-${DIB_NVIDIA_VERSION})

case $DISTRO_NAME in
    centos*|rhel*)
	KERNEL_VERSION=$(ls /boot/vmlinuz*x86_64 | sort -n | tail -n1 | cut -d- -f2-)
	yum install -y kernel-devel-$KERNEL_VERSION kernel-headers-$KERNEL_VERSION
	yum install -y ${NVIDIA_PKGLIST[@]}
	;;
    ubuntu*|debian*)
	KERNEL_VERSION="$(ls /boot/vmlinuz*generic | sort -n | tail -n1 | cut -d- -f2-)"
	apt-get -y install linux-headers-$KERNEL_VERSION
	apt-get -y install ${NVIDIA_PKGLIST[@]}
	;;
    *)
	echo "Distro \"$DISTRO_NAME\" is not recognised"
	exit -1
	;;
esac
