--
- local_loop:
    name: image0
 
- partitioning:
    base: image0
    label: gpt
    partitions:
      - name: ESP
        type: 'EF00'
        size: 2GiB
        mkfs:
          type: vfat
          mount:
            mount_point: /boot/efi
            fstab:
              options: "defaults"
              fsck-passno: 1
      - name: BSP
        type: 'EF02'
        size: 8MiB
      - name: boot
        flags: [ boot ]
        size: 2GiB
        mkfs:
          type: xfs
          mount:
            mount_point: /boot
            fstab:
              options: "defaults"
              fsck-passno: 1
      - name: system-disk
        size: 100%
 
- lvm:
    name: lvm
    base: [ system-disk ]
    pvs:
      - name: pv
        base: system-disk
        options: [ "--force" ]
    vgs:
      - name: system
        base: [ "pv" ]
        options: [ "--force" ]
    lvs:
      - name: swap
        base: system
        size: 2G
      - name: log
        base: system
        size: 5G
      - name: audit
        base: system
        size: 900M
      - name: root
        base: system
        size: 10G
      - name: home
        base: system
        extents: 100%FREE
- mkfs:
    name: fs_log
    base: log
    type: xfs
    label: "log"
    mount:
        mount_point: /var/log
        fstab:
            options: "rw,relatime"
            fsck-passno: 0
- mkfs:
    name: fs_audit
    base: audit
    type: xfs
    label: "audit"
    mount:
        mount_point: /var/log/audit
        fstab:
            options: "rw,relatime"
            fsck-passno: 0
- mkfs:
    name: fs_root
    base: root
    type: xfs
    label: "img-shadowfs"
    mount:
        mount_point: /
        fstab:
            options: "rw,relatime"
            fsck-passno: 0
- mkfs:
    name: fs_home
    base: home
    type: xfs
    label: "home"
    mount:
        mount_point: /home
        fstab:
            options: "rw,nodev,relatime"
            fsck-passno: 0
