---
dib_init_element: "simple-init"
dib_env_vars:
  http_proxy: "{{ lookup('env','http_proxy') }}"
  https_proxy: "{{ lookup('env','https_proxy') }}"
  DIB_INSTALLTYPE_simple_init: repo
  LANG: C
  LC_ALL: C
  LC_MESSAGES: C
  DIB_IPA_ENABLE_RESCUE: true
  DIB_DEV_USER_USERNAME: "e4user"
  DIB_DEV_USER_PASSWORD: "000000"
  DIB_DEV_USER_PWDLESS_SUDO: "yes"

dib_ipa_elements_path: /usr/local/share/ironic-python-agent-builder
dib_extra_elements_path: []

dib_trace: false
dib_uncompressed: false
dib_clearenv: false
dib_notmpfs: false
dib_offline: false
dib_skipbase: false
dib_arch: "amd64"
dib_imagename: "{{ config_dir }}/kolla/config/ironic/ironic-agent"
dib_imagetype: "raw"
#dib_imagesize:
#dib_imagecache: true
#dib_maxresize:
#dib_mintmpfs:
#dib_mkfsopts:
#dib_qemuopts:
#dib_rootlabel:
#dib_rdelement:
#dib_installtype:
#dib_partitioning:
dib_packages: "biosdevname,htop,vim"
dib_os_release: "bionic"
dib_os_element: "ubuntu"
dib_elements: "ironic-python-agent-ramdisk enable-serial-console devuser extra-hardware"
