---
- name: misc op
  include_tasks: misc.yml

- name: Build bifrost image and push it to a private repo
  docker_image:
    build:
      path: "{{ underground.dir }}/build/bifrost"
      nocache: no
      args:
        bifrost_version: "{{ bifrost_version }}"
        ansible_version: "{{ ansible_version }}"
        testing: "{{ testing }}"
        cli: "{{ cli }}"
        usedib: "{{ usedib }}"
    name: "{{ docker.insecure_registries }}/underground/underground-bifrost"
    debug: yes
    tag: '1.0'
    push: no
    source: build
    force_source: yes

