---
- name: run command configure in bifrost container
  shell: docker exec bifrost_underground bash -l -c "/usr/local/bin/configure.sh"
  become: True
  register: configure

- debug: msg= "{{ configure.stdout }}"
