---
project_group: "openstack"
project_name: "kolla-ansible"

kolla_ansible_source: "{{ install_source }}"
kolla_ansible_source_version: "stable/{{ openstack_release }}"
kolla_ansible_git_repository: "{{ git_server }}/{{ project_group }}/{{ project_name }}"

kolla_globals_file: "{{ config_path }}/kolla/target.yml"
kolla_passwords_file: "{{ config_path }}/globals.d/passwords.yml"

kolla_ceph_keyrings:
  - service: glance
    keyring: "ceph.client.{{ ceph_glance_user }}.keyring"
  - service: cinder
    module: cinder-volume
    keyring: "ceph.client.{{ ceph_cinder_user }}.keyring"
  - service: cinder
    module: cinder-backup
    keyring: "ceph.client.{{ ceph_cinder_user }}.keyring"
  - service: cinder
    module: cinder-backup
    keyring: "ceph.client.{{ ceph_cinder_backup_user }}.keyring"
  - service: nova
    keyring: "ceph.client.{{ ceph_cinder_user }}.keyring"
  - service: nova
    keyring: "ceph.client.{{ ceph_nova_user }}.keyring"
