---
# The options in this file can be overridden in 'globals.yml'

virtualenv:
virtualenv_site_packages: false

# OpenStack version
openstack_release: "{{ underground_openstack_release }}"
openstack_source_version: "{{ 'stable/' if openstack_release != 'master' }}{{ openstack_release }}"

# Ceph version
underground_ceph_release: quincy
ceph_release: quincy


ceph_releases:
  nautilus:
    branch: stable-4.0
  octopus:
    branch: stable-5.0
  pacific:
    branch: stable-6.0
  quincy:
    branch: stable-7.0
  latest:
    branch: master

kolla_versions:
  "1": liberty
  "2": mitaka
  "3": newton
  "4": ocata
  "5": pike
  "6": queen
  "7": rocky
  "8": stein
  "9": train
  "10": ussuri
  "11": victoria
  "12": wallaby
  "13": xena
  "14": yoga
  "15": zed

kolla_releases:
  liberty:
    version: 1
    python_version: 2
    python_interpreter: python
  mitaka:
    version: 2
    python_version: 2
    python_interpreter: python
  newton:
    version: 3
    python_version: 2
    python_interpreter: python
  ocata:
    version: 4
    python_version: 2
    python_interpreter: python
  pike:
    version: 5
    python_version: 2
    python_interpreter: python
  queen:
    version: 6
    python_version: 2
    python_interpreter: python
  rocky:
    version: 7
    python_version: 2
    python_interpreter: python
  stein:
    version: 8
    python_version: 2
    python_interpreter: python
  train:
    version: 9
    python_version: 2
    python_interpreter: python
  ussuri:
    version: 10
    python_version: 3
    python_interpreter: python3
  victoria:
    version: 11
    python_version: 3
    python_interpreter: python3
  wallaby:
    version: 12
    python_version: 3
    python_interpreter: python3
  xena:
    version: 13
    python_version: 3
    python_interpreter: python3
  yoga:
    version: 14
    python_version: 3
    python_interpreter: python3
  zed:
    version: 15
    python_version: 3
    python_interpreter: "{{ virtualenv is none | ternary('python3', virtualenv ~ '/bin/python3') }}"

kolla_python: "{{ kolla_releases[openstack_release]['python_interpreter'] }}"
kolla_python_version: "{{ kolla_releases[openstack_release]['python_version'] }}"

# Valid options are: ['git', 'pip']
#ceph_install_source: "curl"
install_source: "git"

#git_server: "https://git.cloud.e4.lan"
git_server: "https://github.com"
git_repos_directory: "/usr/local/src"

config_path: "{{ CONFIG_DIR | default('/etc/underground') }}"
inventory_file: ""
data_path: "/var/lib/underground"
log_path: "/var/log/underground"
config_owner_user: "{{ ansible_effective_user_id }}"
config_owner_group: "{{ ansible_effective_group_id }}"
ceph_ansible_path: "/usr/local/src/ceph-ansible"
ceph_config_path: "{{ config_path }}/ceph"
kolla_ansible_path: "/usr/local/share/kolla-ansible"
kolla_config_path: "{{ config_path }}/kolla"

underground_dryrun: false

underground_deployment: aio

underground_deployments:
  - aio
  - hci

underground_enable_modules:
  - minimal

underground_public_interface: null

# Public: API (Kolla api_interface)
# Internal: Management (Kolla network_interface)
# External: Provider/External (Kolla neutron_external_interface)
underground_modules:
  minimal:
    enable:
      - glance
      - keystone
      - neutron
      - nova
    parent: null
    vars:
      underground_enable_modules: null
      underground_internal_address: null
      underground_internal_interface: null
      underground_openstack_release: null
      underground_public_address: null
      underground_public_interface: null
      kolla_ansible_path: "{{ kolla_ansible_path }}"
      kolla_config_path: "{{ kolla_config_path }}"
    opts:
      underground_external_interface: null
  desktop:
    enable:
      - horizon
    parent: minimal
    vars: {}
    opts: {}
  base:
    enable:
      - barbican
      - cinder
      - heat
      - horizon
    parent: minimal
    vars: {}
    opts: {}
  paas:
    enable:
      - magnum
      - designate
    parent: base
    vars:
      designate_backend: "bind9"
      designate_ns_record:
        - "ns1.cloud.underground.org"
    opts:
      designate_dnssec_validation: "no"
      designate_recursion: "yes"
      designate_forwarders_addresses: "8.8.8.8; 8.8.4.4"
  nfv:
    enable:
      - tacker
    parent: minimal
    vars: {}
    opts: {}
  storage:
    enable:
      - ceph
      #- manila_backend_cephfs_native
    parent: base
    vars:
      ceph_config_path: "{{ ceph_config_path }}"
      underground_ceph_release: "{{ underground_ceph_release }}"
      underground_storage_interface: "{{ underground_internal_interface }}"
    opts:
      underground_replica_interface: "{{ underground_internal_interface }}"
      underground_storage_single: null
  baremetal:
    enable:
      - ironic
    parent: base
    vars:
      underground_baremetal_interface: null
      underground_baremetal_network: null
      underground_baremetal_address: null
    opts:
      underground_baremetal_gateway: null
      underground_baremetal_dhcp_range: null
      underground_baremetal_allocation_pool_start: null
      underground_baremetal_allocation_pool_end: null
      underground_external_network: null
      underground_external_allocation_pool_start: null
      underground_external_allocation_pool_end: null
      underground_external_gateway: null
      underground_external_vlanid: null
      underground_baremetal_dns: null
      underground_baremetal_image: null

underground_vgpu_enabled: false
underground_vgpu_mdev: "nvidia-563"
underground_pgpu_enabled: false
underground_pgpu_pci: '{ "vendor_id":"10de", "product_id":"2235", "device_type":"type-PF", "name":"nvidia-a40" }'

underground_import_ca: false

underground_ssl_ca: |
  -----BEGIN CERTIFICATE-----
  MIIEjjCCAvagAwIBAgIBATANBgkqhkiG9w0BAQsFADA3MRUwEwYDVQQKDAxDTE9V
  RC5FNC5MQU4xHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yMDAy
  MTkxMzM4MTNaFw00MDAyMTkxMzM4MTNaMDcxFTATBgNVBAoMDENMT1VELkU0LkxB
  TjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBojANBgkqhkiG9w0B
  AQEFAAOCAY8AMIIBigKCAYEA2q8U5y7dwCMQnA+Wx+2Kz0mOqfcZ7xuGvMYPb5Y4
  sYlc4CdtMBdyMOJLg1msAR6d6d3VKg+tskcan04tD/MmroT/8yurPgKGdeL91/TE
  oGbjFn9RAZPCpBxtVFNx/+V0KnN/N4mthnwTssKcbK37OWvvHX1r6Gdk6S/LS5tc
  nvtpgZRDzDch7/IPbcuGCi2FtcPd/g1xMhzc5ucob40e4ALEOs3de8GbJr34i84/
  YPEYDTYYoY8Qvqvnr1W9nR6QrB/0HyMuosuIWuSePRXmUxIMieu4W/dJmBQLbLS8
  Q2vfpQns47R3jgzonhr7H4ePSkwECPpqAZTe633FDHtVc43eWixRxr8B4KZnAUBx
  m8lamBSYUNX2lTDal9njof4vK8gGzAtZ9xH7wxENQgp7c//PZIlrfNHKNGfM+6s6
  eiYsVvh/qu1iD156n7oPWmW4VMDlTpW+hhtmvI+I3e7wbEqCln2hkhzgE8IQGFGg
  edXQ5Fw7Np3eoabLuLZ1bXwJAgMBAAGjgaQwgaEwHwYDVR0jBBgwFoAUU9zg/hA2
  GDSaYuvYFcgbfts/95cwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYw
  HQYDVR0OBBYEFFPc4P4QNhg0mmLr2BXIG37bP/eXMD4GCCsGAQUFBwEBBDIwMDAu
  BggrBgEFBQcwAYYiaHR0cDovL2lwYS1jYS5jbG91ZC5lNC5sYW4vY2Evb2NzcDAN
  BgkqhkiG9w0BAQsFAAOCAYEANEQ98NX38RvH1AKiY94Mfv/y27SAvRLZ9u65qTga
  M5u3s9v+raL56YinmQLQGJcHFhFgQwm+DQlYzNie0R3BC2CWHtc208/vDRUxUd4U
  CeCteovdLBDKTEm+X2Wo16WCUgNP5tx3BjoiVFEaPrnSlThoEvkVePQrNjnH+88F
  lnvglmIaZg6YpnycgVHtFAVfNi/hdD/k1K4LkMCZrMxR4tt8dtnlZVZBDKJCAPeD
  g3JpBzPYdxvecFSncYosjYku1oLUM/UPeOk9Vw4UdzGQtK10icDGT3JpL7BLD7Fa
  0vkwYvEf6lklZvDPvR1SDryucK5ckHEizv3+TnJAHS8xyom+RYrLiAY9M8p1S++t
  DvMP7v6GxX6jTv6d2z6XnZ5c1E+v36FfY+RGG+dIcA4tQliVjPqnIFYakauFUQsE
  hZd1S7eNuQg8E1uOrHqprenjppsB49yBGAxI4/bs961U6rkpDbsIptbCkutMGBWF
  5iY9PBQ/4dOtoRzKF2vCuZ3d
  -----END CERTIFICATE-----

# role/defaults variables that should be in group_vars/all.yml
kolla_ansible_extended_globals:
  api_interface: "{{ underground_internal_interface }}"
  #  ironic_dnsmasq_interface: "{{ api_interface }}"
  #  ironic_dnsmasq_dhcp_range: null
  #  ironic_dnsmasq_default_gateway: null
  #  ironic_inspector_pxe_filter: "{% if enable_neutron | bool %}dnsmasq{% else %}noop{% endif %}"
  #  ironic_ipxe_url: "http://{{ kolla_internal_vip_address | put_address_in_context('url') }}:{{ ironic_ipxe_port }}"
  #  tftp_server: "{{ kolla_internal_vip_address }}"
  #  ironic_inspector_kernel_cmdline_extras: []
