---
kind_version: v0.11.1
kubectl_version: v1.21.0
cluster_name: "{{ underground_cluster_name }}"
kind_create: false
kind_destroy: false
# valid values are ipv4, ipv6, dual
kind_ip_family: ipv4
kind_apiServerPort: 8080
kind_home_dir: '{{ ansible_env.HOME }}/.kind'
kubectl_config_file: '{{ ansible_env.HOME }}/.kube/config'
kind_cluster_config: "kind-cluster-config.yml"
kind_create_config: true
kubectl_create_config: true
kind_worker_enabled: false
kind_custom_registry: false
kind_custom_registry_aliases:
- example.com
- example.org
- test.com
- test.org
container_registry_name: 'kind-registry.local'
container_registry_port: 5000
extra_port_mappings:
  - '0.0.0.0:80:80'
  - '0.0.0.0:443:443'
