#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

wget --no-check-certificate -c $CA_URL -O /usr/local/share/ca-certificates/e4lan.crt
update-ca-certificates
