#!/bin/bash
#
# Copyright 2020 Ettore Simone <ettore.simone@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case $DIB_RELEASE in
    xenial)
        update-alternatives --install /usr/bin/python python /usr/bin/python2 1
        ;;
    bionic|focal)
        update-alternatives --install /usr/bin/python python /usr/bin/python3 1
        ;;
    *)
        echo "Unsupported Ubuntu release $DIB_RELEASE"
        exit 1
esac
