---
- name: Install required packages
  become: true
  package:
    name: "{{ packages_all }}"

- name: Install custom packages
  become: true
  package:
    name: "{{ packages_custom }}"

- include_tasks: "uninstall.yml"
  when: "ansible_system == 'Linux'"

- include_tasks: "{{ kolla_build_source }}.yml"
