#!/bin/bash
#
# Copyright 2019 Ettore Simone <ettore.simone@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -d /etc/default/grub.d ]; then
    rm -rf /etc/default/grub.d
fi
if [ -f /etc/default/grub ]; then
    sed -e 's/console=ttyS[0-9][,0-9noer]*//;s/console=hvc[0-9]//' \
        -e '/GRUB_TERMINAL="serial console"/d' \
        -i /etc/default/grub
    
fi
# FIXME: centos grub error "you need to load the kernel first"
ln -s . /boot/boot
if [ -d /boot/grub2 ]; then
    GRUB_CFG=/boot/grub2/grub.cfg
elif [ -d /boot/grub ]; then
    GRUB_CFG=/boot/grub/grub.cfg
fi
if type grub2-mkconfig >/dev/null; then
    GRUB_MKCONFIG="grub2-mkconfig -o $GRUB_CFG"
else
    GRUB_MKCONFIG="grub-mkconfig -o $GRUB_CFG"
fi
cat >>/etc/default/grub <<EOD
GRUB_TIMEOUT_STYLE=menu
GRUB_DISABLE_OS_PROBER=true
EOD
$GRUB_MKCONFIG
