---

- name: Create Underground cache config directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  loop:
    - "{{ data_path }}/baremetal/cache"
  become: true

