---
- name: Install required packages
  become: true
  package:
    name:
      - libffi-dev
      - libssl-dev

- name: Cloning ironic-python-agent-builder source repository
  git:
    repo: "{{ ipa_build_git_repository }}"
    dest: "{{ git_repos_directory }}/{{ project_name_ipa }}"
    update: yes
    version: "{{ ipa_build_source_version }}"

- name: Install ironic-python-agent-builder
  become: true
  command: "{{ kolla_python }} -m pip install {{ git_repos_directory }}/{{ project_name_ipa }}"


- name: Cloning diskimage-builder source repository
  git:
    repo: "{{ dib_build_git_repository }}"
    dest: "{{ git_repos_directory }}/{{ project_name }}"
    update: yes
    version: "{{ dib_build_source_version }}"

- name: Install diskimage-builder
  become: true
  command: "{{ kolla_python }} -m pip install {{ git_repos_directory }}/{{ project_name }}"
