---
- name: Install required packages
  become: true
  package:
    name: "{{ packages_all }}"
  when: packages_all is defined

- name: Install custom packages
  become: true
  package:
    name: "{{ packages_custom }}"
  when: packages_custom is defined

- name: Manages Python library dependencies
  become: "{{ virtualenv is none }}"
  pip:
    name: "{{ packages_python }}"
    executable: "{{ virtualenv is none | ternary('pip3', omit) }}"
    virtualenv: "{{ virtualenv is none | ternary(omit, virtualenv) }}"
    virtualenv_site_packages: "{{ virtualenv is none | ternary(omit, virtualenv_site_packages) }}"
    virtualenv_command: "{{ virtualenv is none |  ternary(omit, 'python' ~  kolla_releases[openstack_release]['python_version'] ~ ' -m venv') }}"  
  when: packages_python is defined

- include_tasks: "{{ kolla_build_source }}.yml"
