---
- include_tasks: "{{ group }}.yml"
  when: group in group_names
  loop:
    - control
    - monitoring
    - network
    - compute
    - storage
  loop_control:
    loop_var: group

- name: Collect only facts returned by facter
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - network

- name: Check if we are inside a container
  stat:
    path: "/.dockerenv"
  register: dockerin
  delegate_to: "{{ groups['deployment'][0] }}"
  run_once: true

- name: Debug Conditions in container
  debug:
    msg: "{{ dockerin.stat.exists }}"

- name: Ensure hostname match IP address
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '.*\s+{{ ansible_hostname }}(\s|$)'
    line: "{{ hostvars[inventory_hostname]['ansible_'+underground_internal_interface]['ipv4']['address'] }}\t{{ ansible_hostname }}"
    state: present
    unsafe_writes: "{{ dockerin.stat.exists|default('false')|bool }}"
  vars:
    kolla_globals: "{{ hostvars['localhost']['kolla_globals'] }}"
