---
- name: Create systemd network directory
  become: true
  file:
    path: /etc/systemd/network
    state: directory
    mode: '0755'

- name: Create Netplan Neutron External Interfaces
  become: true
  template:
    src: "neutron-{{ item }}.yaml.j2"
    dest: "/etc/netplan/90-neutron-{{ item }}.yaml"
    mode: '0644'
  when: item in ['minimal', 'baremetal']
  loop: "{{ hostvars['localhost']['underground_list_modules'] }}"

- name: Apply Netplan
  become: true
  command: netplan apply
