#!/bin/bash
#
# Copyright 2019 Ettore Simone <ettore.simone@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -d /etc/cloud/cloud.cfg.d ]; then
    CLOUD_CFG=/etc/cloud/cloud.cfg.d/99-custom-growpart.cfg
elif [ -f /etc/cloud/cloud.cfg ]; then
    CLOUD_CFG=/etc/cloud/cloud.cfg
fi

if [ -n "${CLOUD_CFG:-}" -a -f /tmp/in_target.d/growpart.cfg ]; then
    cat /tmp/in_target.d/growpart.cfg >> ${CLOUD_CFG}
fi
