#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

DIB_CLOUD_INIT_NVIDIA_DOCKER='growpart:
    mode: auto
    devices: ["/var/lib/docker"]
    ignore_growroot_disabled: true'

if [ -d /etc/cloud/cloud.cfg.d ]; then
    echo "$DIB_CLOUD_INIT_NVIDIA_DOCKER" >/etc/cloud/cloud.cfg.d/91-dib-nvidia-docker.cfg
elif [ -f /etc/cloud/cloud.cfg ]; then
    echo "$DIB_CLOUD_INIT_NVIDIA_DOCKER" >>/etc/cloud/cloud.cfg
fi
