---
- name: Uninstall old versions
  become: true
  package:
    state: absent
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

- name: Install required packages
  become: true
  package:
    name:
      - yum-utils

- name: Setup stable Docker repository
  become: true
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker CE
  become: true
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Activate Docker service
  become: true
  service:
    name: docker
    enabled: yes
    state: started
