---
- name: Create /etc/docker directory
  become: true
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

#- name: Create daemon.json configuration
#  become: true
#  template:
#    src: docker-daemon.json.j2
#    dest: /etc/docker/daemon.json
#    mode: '0640'

- name: Create daemon.json configuration
  become: true
  json_merge:
    path: /etc/docker/daemon.json
    data: "{{ docker_daemon_json }}"
    default: true

- name: Set registry-mirrors
  become: true
  json_merge:
    path: /etc/docker/daemon.json
    data:
      registry-mirrors:
        - "http://192.168.33.1:4000"
  when: "'deployment' not in group_names"

- include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Install Docker Python binding
  become: true
  pip:
    name: docker

- name: Get info on docker host
  become: true
  docker_host_info:
  register: docker_info
  failed_when: false

- name: Ensure Docker is running
  fail:
    msg: "Docker on {{ inventory_hostname }} is not responsive:\n{{ docker_info.msg }}"
  when: not docker_info.can_talk_to_docker|default(true)
