---
#- import_playbook: gather-facts.yml

- name: "Low level pre-requisite (action: {{ underground_action }})"
  hosts: deployment
  gather_facts: true
  roles:
    - { role: pre-requisite,
        tags: pre-requisite }

- name: "Common roles (action: {{ underground_action }})"
  hosts: deployment
  roles:
    - { role: common,
        tags: common }

          #- name: "Ceph Ansible (action: {{ underground_action }})"
          #  hosts: deployment
          #  roles:
          #    - { role: ceph-ansible,
          #        tags: ceph-ansible }

          #- name: "Kolla (action: {{ underground_action }})"
          #  hosts: deployment
          #  roles:
          #    - { role: kolla-build,
          #        tags: kolla-build }

- name: "Kolla Ansible (action: {{ underground_action }})"
  hosts: deployment
  roles:
    - { role: kolla-ansible,
        tags: kolla-ansible }

- name: "OpenStack client (action: {{ underground_action }})"
  hosts: deployment
  roles:
    - { role: openstack-client,
        tags: openstack-client }
