---
- name: kind-underground
  hosts: localhost
  connection: local
  become: True
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    cluster_name: '{{ underground_cluster_name }}'
    underground_action: deploy
  roles:
    - role: kind
