#!/bin/bash
#
# Copyright 2019 Ettore Simone <ettore.simone@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
  
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case $DISTRO_NAME in
    debian|ubuntu)
        # Add the key
        curl -fsSL https://download.docker.com/linux/$DISTRO_NAME/gpg | apt-key add -
        echo "deb [arch=$ARCH] https://download.docker.com/linux/$DISTRO_NAME $DIB_RELEASE stable" >>/etc/apt/sources.list.d/docker-ce.list
        install-packages apt-transport-https ca-certificates gnupg2
        ;;
    centos*|rhel*)
        curl -o /etc/yum.repos.d/docker-ce.repo -fsSL https://download.docker.com/linux/centos/docker-ce.repo
        ;;
esac
