---
pkgreq:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-docker
  - python3-kubernetes

pkgdocker:
  - docker-ce
  - docker-ce-cli
  - containerd.io
