---
- name: Set OS distribution dependent variables
  include_vars: "{{ ansible_facts['distribution'] }}.yaml"

- name: Create docker directory
  file:
    state: directory
    path: /etc/docker

- name: Install docker-ce from upstream
  include: upstream.yaml
  when: use_upstream_docker|bool

- name: Install docker-engine from distro
  include: distro.yaml
  when: not use_upstream_docker|bool

- name: reset ssh connection to pick up docker group
  meta: reset_connection

- name: Add docker daemon config file
  template:
    dest: /etc/docker/daemon.json
    group: root
    mode: 0644
    owner: root
    src: daemon.json.j2
  notify: 'Restart Docker'

- name: Install docker-compose from pip
  include: compose.yaml

- name: Flush handlers
  meta: flush_handlers
