#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


case $DISTRO_NAME in
    centos*|rhel*)
	LOCATIONS="/etc/default/grub /etc/grub.d/*"
	;;
    ubuntu*|debian*)
	LOCATIONS="/etc/default/grub /etc/default/grub.d/* /etc/grub.d/*"
	;;
esac

for i in $LOCATIONS; 
do
  if ! [ -f $i ]; then
    continue
  fi
  sed -i 's/console=ttyS[0-9][,0-9noer]*//;s/console=hvc[0-9]//' $i
done
