name: install-underground-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-underground:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt -y install python3-pip
      - run: sudo pip install ./
      - run: sudo underground init aio
      - run: sudo underground bootstrap xena -m baremetal -e@contrib/vars/underground_baremetal_vars.yml
      - run: sudo underground build     -t dib -e underground_baremetal_image="underground" 
      - run: sudo underground configure

