name: install-underground-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-underground:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout
        repository: ''
      - run: pip install ./
      - run: underground init aio

