name: install-underground-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-underground:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
         
      - run: pip install ./
      - run: underground init aio

