# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pkg Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tox:

    runs-on: [self-hosted, linux, x64]
    container: ubuntu:22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.6"
    - name: Install OS pkg
      shell: bash
      run: |
        apt-get update -qq
        apt-get install -qq -y gcc python3-pip git
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      shell: bash
      run: |
        # test default build and modules
        python -m tox -e linting,modules